### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by alper95polat** [hanseartic/stellar-resolve-claimant-predicates#18]
Hi, I want to use this package but after installation the app crashes instantly and throws:

```
evalPredicates.js:5 Uncaught ReferenceError: exports is not defined
    at ./node_modules/stellar-resolve-claimant-predicates/dist/evalPredicates.js (evalPredicates.js:5:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/popup/blocks/ClaimableBalances/index.tsx (index.tsx:15:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/popup/pages/ClaimableBalances/index.tsx (index.tsx:8:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/popup/pages/index.tsx (index.tsx:43:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/popup/index.tsx (index.tsx:9:1)
    at __webpack_require__ (bootstrap:19:1)
```

My [webpack config file](https://github.com/rabetofficial/rabet-extension/blob/master/webpack.config.js)
Nodejs: v16.14.0
npm: 6.14.16

**Comment by hanseartic** [comment]
Thank you for reporting. I need to look into this.

**Comment by hanseartic** [comment]
@alper95polat 
I changed transforming typescript to use babel. Can you give it another shot with `v2.0.9`. And if that does not do, could you try with `v2.0.6` (that was before the typescript conversion), please?
